name: Build/Publish

on:
    push:
        branches:
            - master
            - develop
            - develop-*
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   name: Use Node.js
                uses: actions/setup-node@v3
                with:
                    node-version: 18.x
                    cache: 'npm'
            -   run: npm ci
            -   run: npm run build --if-present
                env:
                    NODE_OPTIONS: "--max_old_space_size=4096"
            -   name: Install SSH key
                uses: shimataro/ssh-key-action@v2
                with:
                    key: ${{ secrets.GITEA_SSH_KEY }}
                    known_hosts: ${{ secrets.GITEA_KNOWN_HOST }}
            -   name: Publish
                run: npm run semantic-release
